### ISSUE TITLE
Module '“angular2/angular2”' has no exported member 'For'

### ISSUE THREAD

**Issue by juanpasolano** [fcoury/angular2-webpack-typescript#2]
The book is telling me to use For, but I think it has changed to NgFor

**Comment by juanpasolano** [comment]
also in the template its *ng-for not *for

**Comment by fcoury** [comment]
Hi @juanpasolano that was a recent change to the AngularJS code and it's now reflected both in the book and in the code. You should always use `NgFor` and `*ng-for=` from now on.

Please note that the `properties` property for `@Component` also changed. Check the update for more information or ping me here if you need.

**Comment by juanpasolano** [comment]
Thank you... good to know it has been updated

**Comment by juanpasolano** [comment]
How can i get the updated version of the PDF

**Comment by fcoury** [comment]
@juanpasolano you just need to get the email you got when you first bought the book and look for the "View product" link. When you click it, you'll see the `ng-book2-r2.pdf` file.

Let me know if it works for you.
